debug:
  verbose: true

server:
  listen: 7004

  index: control/index.md

  page:
    title: Loopin Base Project
    nav:
      - title: Example
        page: control/index.md

      - title: Utility
        page: control/utility.md

  # This is the file that will store persistence for
  # your application.
  persist: data/persist.yaml

  # These directories will be shared under:
  #   http://localhost/files/*
  dirs:
    - control
    - preset
    - shader
    - image
    - data
